// frontend/src/views/Login.vue
<template>
  <div class="login-container">
    <div class="login-box">
      <n-card class="auth-card" size="large" hoverable>
        <div class="header">
          <h1 class="title">MusicGraph</h1>
          <p class="subtitle">探索你的音乐思维轨迹</p>
        </div>

        <n-tabs 
          v-model:value="activeTab" 
          size="large" 
          justify-content="space-evenly"
          type="segment"
          animated
        >
          <n-tab-pane name="login" tab="登录" />
          <n-tab-pane name="register" tab="注册" />
        </n-tabs>

        <div class="form-area">
          <n-input
            v-model:value="form.username"
            size="large"
            placeholder="请输入账号"
          >
            <template #prefix>
              <n-icon :component="PersonOutline" />
            </template>
          </n-input>

          <n-input
            v-model:value="form.password"
            type="password"
            show-password-on="click"
            size="large"
            placeholder="请输入密码"
            @keyup.enter="handleAuth"
          >
            <template #prefix>
              <n-icon :component="LockClosedOutline" />
            </template>
          </n-input>

          <n-button
            type="primary"
            size="large"
            block
            :loading="loading"
            @click="handleAuth"
            :disabled="!form.username || !form.password"
            class="submit-btn"
          >
            {{ activeTab === 'login' ? '立即登录' : '注册账号' }}
          </n-button>
        </div>
      </n-card>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive } from 'vue'
import { useRouter } from 'vue-router'
import { useUserStore } from '../store/user'
import { NCard, NInput, NButton, NIcon, NTabs, NTabPane, useMessage } from 'naive-ui'
import { PersonOutline, LockClosedOutline } from '@vicons/ionicons5'
import request from '../api/request'

const router = useRouter()
const userStore = useUserStore()
const message = useMessage()

const activeTab = ref('login')
const loading = ref(false)

const form = reactive({
  username: '',
  password: ''
})

const handleAuth = async () => {
  if (!form.username.trim() || !form.password.trim()) {
    message.warning('账号和密码不能为空')
    return
  }

  loading.value = true

  try {
    if (activeTab.value === 'login') {
      const res = await request.post('/auth/login', null, {
        params: {
          username: form.username,
          password: form.password
        }
      })
      
      const { token, username } = res.data
      localStorage.setItem('token', token)
      userStore.setUsername(username)
      
      message.success('登录成功，欢迎回来！')
      router.push('/')

    } else {
      await request.post('/auth/register', null, {
        params: {
          username: form.username,
          password: form.password
        }
      })
      
      message.success('注册成功，请登录')
      activeTab.value = 'login'
    }
  } catch (error: any) {
    const msg = error.response?.data || '请求失败，请检查网络'
    message.error(msg)
  } finally {
    loading.value = false
  }
}
</script>

<style scoped>
.login-container {
  /* 使用 100% 充满父容器（App.vue 的 content 区域） */
  width: 100%;
  height: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
  /* 移除写死的背景色，依靠透明背景显示 App.vue 的底色 */
}

.login-box {
  width: 400px;
  max-width: 90%;
  z-index: 1;
}

.auth-card {
  border-radius: 16px;
  /* 增加一点阴影让它在浅色模式下更立体 */
  box-shadow: 0 4px 24px rgba(0, 0, 0, 0.1);
}

.header {
  text-align: center;
  margin-bottom: 24px;
}

.title {
  font-size: 2rem;
  font-weight: 700;
  /* 使用渐变色作为品牌标识 */
  background: linear-gradient(to right, #1db954, #1ed760);
  -webkit-background-clip: text;
  color: transparent;
  margin: 0;
}

.subtitle {
  /* 使用 Naive UI 的变量让副标题颜色自动适配深浅 */
  color: var(--n-text-color-3); 
  margin-top: 8px;
}

.form-area {
  display: flex;
  flex-direction: column;
  gap: 20px;
  margin-top: 24px;
}

.submit-btn {
  font-weight: bold;
  letter-spacing: 1px;
}

/* 移除所有 :deep 的 !important 样式覆盖 */
/* 让 Naive UI 自动处理 Input 和 Tabs 的颜色 */
</style>

// nocode-frontend/src/pages/Login.jsx
import { User, Lock, Eye, EyeOff } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { toast } from 'sonner';
import request from '../utils/request';
import { useAuth } from '../hooks/useAuth';
import { useState } from 'react';
const Login = () => {
  const [activeTab, setActiveTab] = useState('login');
  const [form, setForm] = useState({
    username: '',
    password: ''
  });
  const [showPassword, setShowPassword] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');
  const navigate = useNavigate();
  const { login } = useAuth();

  const handleAuth = async (e) => {
    e.preventDefault();
    setIsLoading(true);
    setError('');

    if (!form.username.trim() || !form.password.trim()) {
      setError('账号和密码不能为空');
      setIsLoading(false);
      return;
    }

    try {
      if (activeTab === 'login') {
        const response = await request.post('/auth/login', null, {
          params: {
            username: form.username,
            password: form.password
          }
        });
        
        const { token, username } = response.data;
        localStorage.setItem('token', token);
        localStorage.setItem('isLoggedIn', 'true'); // 显式设置登录状态
        login(username);
        
        // 显示登录成功提示
        toast.success('登录成功，欢迎回来！');
        
        // 延迟跳转，确保状态更新完成
        setTimeout(() => {
          navigate('/', { replace: true });
        }, 100);
      } else {
        await request.post('/auth/register', null, {
          params: {
            username: form.username,
            password: form.password
          }
        });
        
        // 显示注册成功提示
        toast.success('注册成功，请登录');
        setActiveTab('login');
      }
    } catch (error) {
      // 确保错误信息是字符串类型
      let errorMessage = '';
      if (error.response?.data) {
        errorMessage = typeof error.response.data === 'string' 
          ? error.response.data 
          : JSON.stringify(error.response.data);
      } else if (error.message) {
        errorMessage = error.message;
      } else {
        errorMessage = '请求失败，请检查网络';
      }
      setError(errorMessage);
    } finally {
      setIsLoading(false);
    }
  };

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setForm(prev => ({
      ...prev,
      [name]: value
    }));
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-blue-50 to-indigo-100">
      <div className="max-w-md w-full space-y-8 p-8">
        <div className="bg-white rounded-lg shadow-xl p-8">
          <div className="text-center mb-8">
            <h1 className="text-3xl font-bold bg-gradient-to-r from-green-500 to-green-600 bg-clip-text text-transparent">
              MusicGraph
            </h1>
            <p className="mt-2 text-sm text-gray-600">探索你的音乐思维轨迹</p>
          </div>

          <div className="flex mb-6 bg-gray-100 rounded-lg p-1">
            <button
              className={`flex-1 py-2 px-4 rounded-md text-sm font-medium transition-colors ${
                activeTab === 'login'
                  ? 'bg-white text-blue-600 shadow-sm'
                  : 'text-gray-600 hover:text-gray-900'
              }`}
              onClick={() => setActiveTab('login')}
            >
              登录
            </button>
            <button
              className={`flex-1 py-2 px-4 rounded-md text-sm font-medium transition-colors ${
                activeTab === 'register'
                  ? 'bg-white text-blue-600 shadow-sm'
                  : 'text-gray-600 hover:text-gray-900'
              }`}
              onClick={() => setActiveTab('register')}
            >
              注册
            </button>
          </div>

          <form onSubmit={handleAuth} className="space-y-6">
            <div>
              <div className="relative">
                <User className="absolute left-3 top-1/2 transform -translate-y-1/2 h-5 w-5 text-gray-400" />
                <input
                  type="text"
                  name="username"
                  value={form.username}
                  onChange={handleInputChange}
                  className="w-full pl-10 pr-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  placeholder="请输入账号"
                  required
                />
              </div>
            </div>

            <div>
              <div className="relative">
                <Lock className="absolute left-3 top-1/2 transform -translate-y-1/2 h-5 w-5 text-gray-400" />
                <input
                  type={showPassword ? 'text' : 'password'}
                  name="password"
                  value={form.password}
                  onChange={handleInputChange}
                  className="w-full pl-10 pr-12 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  placeholder="请输入密码"
                  required
                />
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute right-3 top-1/2 transform -translate-y-1/2 h-5 w-5 text-gray-400 hover:text-gray-600"
                >
                  {showPassword ? <EyeOff /> : <Eye />}
                </button>
              </div>
            </div>

            {error && (
              <div className={`text-sm text-center p-3 rounded-lg ${
                (typeof error === 'string' && error.includes('成功'))
                  ? 'text-green-600 bg-green-50' 
                  : 'text-red-600 bg-red-50'
              }`}>
                {error}
              </div>
            )}

            <button
              type="submit"
              disabled={isLoading || !form.username || !form.password}
              className="w-full bg-blue-600 text-white py-3 px-4 rounded-lg hover:bg-blue-700 focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed transition duration-200 font-bold tracking-wide"
            >
              {isLoading ? '处理中...' : activeTab === 'login' ? '立即登录' : '注册账号'}
            </button>
          </form>
        </div>
      </div>
      <div className="fixed bottom-4 right-4 text-xs text-gray-500 text-right">
        前端使用美团nocode生成，<br />
        前后端及本地部署代码已开源至<br />
        <a 
          href="https://github.com/ouroborosscr/MusicGraph" 
          target="_blank" 
          rel="noopener noreferrer"
          className="text-blue-600 hover:underline"
        >
          https://github.com/ouroborosscr/MusicGraph
        </a>
      </div>
    </div>
  );
};

export default Login;
