// nocode-frontend/src/pages/Player.jsx
import { useEffect, useState, useRef, useCallback } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useAuth } from '../hooks/useAuth';
import { ArrowLeft, Play, Plus, Minus, MoveDiagonal } from 'lucide-react';
import Navbar from '../components/Navbar';
import * as echarts from 'echarts';
import request from '../utils/request';

const Player = () => {
  const { id } = useParams()
  const navigate = useNavigate()
  const { isLoggedIn } = useAuth()
  
  // ================= 1. 使用 useRef 存储实例 (关键优化) =================
  const chartRef = useRef(null)
  const boxRef = useRef(null)
  const chartInstance = useRef(null) // 不会触发重渲染

  const [loading, setLoading] = useState(true)
  const [graphName, setGraphName] = useState('加载中...')
  const [nodeCount, setNodeCount] = useState(0)
  const [currentZoom, setCurrentZoom] = useState(0.3)

  // 拖拽状态
  const [resizeState, setResizeState] = useState({
    isResizing: false,
    width: 0,
    height: 0,
    startX: 0,
    startY: 0,
    startWidth: 0,
    startHeight: 0,
    resizeMode: ''
  })

  // ================= 2. 渲染图表逻辑 (初始化 + 更新) =================
  const renderChart = useCallback((nodes, links) => {
    if (!chartRef.current) return
    
    // A. 懒初始化：只有实例不存在时才 init
    if (!chartInstance.current) {
      chartInstance.current = echarts.init(chartRef.current)
      
      // 事件监听只绑定一次
      chartInstance.current.on('click', (params) => {
        if (params.dataType === 'node') {
          console.log(`选中歌曲: ${params.data.name}`)
        }
      })
      
      chartInstance.current.on('graphRoam', (params) => {
        if (params.zoom) {
          setCurrentZoom(prev => prev * params.zoom)
        }
      })
    }
    
    // B. 数据更新
    const option = {
      backgroundColor: 'transparent',
      title: { show: false },
      tooltip: {
        trigger: 'item',
        backgroundColor: '#ffffff',
        borderColor: '#e5e7eb',
        textStyle: { color: '#374151' },
        formatter: (params) => {
          if (params.dataType === 'node') {
            return `<b>${params.data.name}</b><br/>歌手: ${params.data.artist}`
          }
          return `${params.data.source} -> ${params.data.target}<br/>权重: ${params.data.value}`
        }
      },
      series: [
        {
          type: 'graph',
          layout: 'force',
          layoutAnimation: true,
          zoom: currentZoom,
          label: { 
            show: true, 
            position: 'right', 
            color: '#66ccff', 
            fontSize: 12 
          },
          data: nodes.map(n => ({
            id: n.id,
            name: n.name,
            symbolSize: n.symbolSize || 20,
            value: n.artist,
            artist: n.artist,
            x: n.x,
            y: n.y,
            itemStyle: { 
              color: '#66ccff', 
              borderColor: '#4dabf7', 
              borderWidth: 1, 
              shadowBlur: 10, 
              shadowColor: 'rgba(102, 204, 255, 0.5)' 
            }
          })),
          links: links.map(l => ({
            source: l.source,
            target: l.target,
            value: l.value,
            lineStyle: { 
              width: Math.min(l.value, 5), 
              curveness: 0.2, 
              color: '#66ccff', 
              opacity: 0.3 
            }
          })),
          roam: true,
          edgeSymbol: ['none', 'arrow'],
          edgeSymbolSize: [4, 10],
          force: { 
            repulsion: 400, 
            edgeLength: [50, 200], 
            gravity: 0.1 
          }
        }
      ]
    }

    // 设置配置项
    chartInstance.current.setOption(option, { notMerge: true })
    
    // 【核心修复】数据加载完成后，强制触发一次 resize
    // 这能确保图表立即填满容器，不需要等待下一次交互
    setTimeout(() => {
        chartInstance.current?.resize();
    }, 10);
    
  }, [currentZoom]) 

  // ================= 3. 数据获取 =================
  const fetchData = useCallback(async () => {
    setLoading(true)
    try {
      const response = await request.get(`/graph/data/${id}`)
      const { nodes, links } = response.data
      setNodeCount(nodes.length)
      setGraphName(`图谱 #${id}`)
      
      const processedNodes = nodes.map(n => ({
        ...n,
        x: Math.random() * 800,
        y: Math.random() * 600
      }))
      
      // 数据准备好后渲染
      setTimeout(() => {
        renderChart(processedNodes, links)
      }, 50)
    } catch (error) {
      console.error('无法加载图谱数据:', error)
    } finally {
      setLoading(false)
    }
  }, [id, renderChart])

  // ================= 4. 生命周期管理 =================
  useEffect(() => {
    const hasToken = localStorage.getItem('token');
    const isLoggedInStorage = localStorage.getItem('isLoggedIn') === 'true';

    if (!isLoggedIn && !hasToken && !isLoggedInStorage) {
      navigate('/login');
      return;
    }
    
    fetchData();
    
    return () => {
      if (chartInstance.current) {
        chartInstance.current.dispose();
        chartInstance.current = null;
      }
    }
  }, [isLoggedIn, navigate, fetchData])

  // ================= 5. 拖拽缩放逻辑 =================
  const startResize = (e, mode) => {
    e.preventDefault();
    if (!boxRef.current) return;
    const rect = boxRef.current.getBoundingClientRect();
    setResizeState({
      isResizing: true, resizeMode: mode, startX: e.clientX, startY: e.clientY,
      startWidth: rect.width, startHeight: rect.height,
      width: resizeState.width || rect.width, height: resizeState.height || rect.height
    });
  };

  useEffect(() => {
    const handleMouseMove = (e) => {
      if (!resizeState.isResizing) return;
      const dx = e.clientX - resizeState.startX;
      const dy = e.clientY - resizeState.startY;
      const minSize = 300;
      let newWidth = resizeState.width;
      let newHeight = resizeState.height;

      if (resizeState.resizeMode === 'width' || resizeState.resizeMode === 'both') 
        newWidth = Math.max(minSize, resizeState.startWidth + dx);
      if (resizeState.resizeMode === 'height' || resizeState.resizeMode === 'both') 
        newHeight = Math.max(minSize, resizeState.startHeight + dy);

      setResizeState(prev => ({ ...prev, width: newWidth, height: newHeight }));
    };

    const handleMouseUp = () => {
      if (resizeState.isResizing) {
        setResizeState(prev => ({ ...prev, isResizing: false }));
        chartInstance.current?.resize(); // 拖拽结束重置图表大小
      }
    };

    if (resizeState.isResizing) {
      document.addEventListener('mousemove', handleMouseMove);
      document.addEventListener('mouseup', handleMouseUp);
      document.body.style.userSelect = 'none';
      document.body.style.cursor = 'nwse-resize';
    }
    return () => {
      document.removeEventListener('mousemove', handleMouseMove);
      document.removeEventListener('mouseup', handleMouseUp);
      document.body.style.userSelect = '';
      document.body.style.cursor = '';
    };
  }, [resizeState]);

  // 监听容器大小变化 (自动修正显示问题的关键)
  useEffect(() => {
    if (!boxRef.current) return;
    const resizeObserver = new ResizeObserver(() => {
      chartInstance.current?.resize();
    });
    resizeObserver.observe(boxRef.current);
    return () => resizeObserver.disconnect();
  }, []);

  const boxStyle = {
    minHeight: '600px',
    position: 'relative',
    ...(resizeState.width > 0 ? { width: `${resizeState.width}px`, flex: 'none' } : { flex: 1 }),
    ...(resizeState.height > 0 ? { height: `${resizeState.height}px` } : {}),
  };

  const handleZoom = (ratio) => {
    const newZoom = currentZoom * ratio
    if (newZoom >= 0.1 && newZoom <= 10) {
      setCurrentZoom(newZoom)
      if (chartInstance.current) {
        chartInstance.current.setOption({ series: [{ zoom: newZoom }] })
      }
    }
  }

  const goBack = () => navigate('/')

  if (!isLoggedIn && localStorage.getItem('isLoggedIn') === 'true') {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto mb-4"></div>
          <p className="text-gray-600">身份同步中...</p>
        </div>
      </div>
    );
  }

  if (!isLoggedIn) return null;

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col">
      <Navbar />
      <div className="flex-1 flex flex-col p-4 overflow-hidden">
        <div className="bg-white border-b border-gray-200 px-6 py-4 flex items-center justify-between rounded-lg shadow-sm mb-4 shrink-0">
          <div className="flex items-center space-x-4">
            <button onClick={goBack} className="p-2 hover:bg-gray-100 rounded-full transition-colors">
              <ArrowLeft className="h-5 w-5 text-gray-600" />
            </button>
            <div>
              <h2 className="text-xl font-semibold text-gray-900">{graphName}</h2>
              <span className="text-sm text-gray-500">包含 {nodeCount} 首歌曲</span>
            </div>
          </div>
          <button className="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-colors flex items-center space-x-2">
            <Play className="h-4 w-4" />
            <span>随机播放</span>
          </button>
        </div>

        {/* 这一层 div 是关键，包含了 ref={boxRef} 和拖拽手柄 */}
        <div 
          ref={boxRef}
          className={`bg-white rounded-xl shadow-sm border-2 border-dashed border-gray-300 relative transition-colors duration-200 ${resizeState.isResizing ? 'border-blue-400' : 'hover:border-blue-300'}`}
          style={boxStyle}
        >
          {loading && (
            <div className="absolute inset-0 bg-white bg-opacity-90 flex items-center justify-center z-20 rounded-xl">
              <div className="text-center">
                <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto mb-4"></div>
                <p className="text-gray-600">正在加载星图...</p>
              </div>
            </div>
          )}
          
          <div ref={chartRef} className="w-full h-full rounded-xl overflow-hidden"></div>

          <div className="absolute bottom-6 right-6 flex flex-col space-y-2 z-10">
            <button onClick={() => handleZoom(1.2)} className="bg-white border border-gray-300 rounded-lg p-2 hover:bg-gray-50 transition-colors shadow-sm">
              <Plus className="h-4 w-4 text-gray-600" />
            </button>
            <button onClick={() => handleZoom(0.8)} className="bg-white border border-gray-300 rounded-lg p-2 hover:bg-gray-50 transition-colors shadow-sm">
              <Minus className="h-4 w-4 text-gray-600" />
            </button>
          </div>

          {/* 拖拽手柄 (Resize Handles) - 之前你的代码里缺了这些 */}
          <div className="absolute top-0 right-0 bottom-6 w-4 cursor-ew-resize hover:bg-blue-500/10 z-20" onMouseDown={(e) => startResize(e, 'width')}></div>
          <div className="absolute bottom-0 left-0 right-6 h-4 cursor-ns-resize hover:bg-blue-500/10 z-20" onMouseDown={(e) => startResize(e, 'height')}></div>
          <div className="absolute bottom-0 right-0 w-8 h-8 cursor-nwse-resize bg-white border-t border-l border-gray-200 rounded-tl-lg flex items-center justify-center hover:bg-blue-50 z-30" onMouseDown={(e) => startResize(e, 'both')}>
            <MoveDiagonal className="h-4 w-4 text-gray-400" />
          </div>
        </div>
      </div>
    </div>
  )
}

export default Player;

// frontend/src/views/Player.vue
<template>
  <div class="player-container" ref="containerRef">
    <div class="player-header">
      <div class="left">
        <n-button circle secondary @click="goBack">
          <template #icon><n-icon><ArrowBack /></n-icon></template>
        </n-button>
        <div class="info">
          <h2>{{ graphName }}</h2>
          <span class="status">包含 {{ nodeCount }} 首歌曲</span>
        </div>
      </div>
      <div class="right">
        <n-button type="primary" size="small" round>
          <template #icon><n-icon><Play /></n-icon></template>
          随机播放
        </n-button>
      </div>
    </div>

    <div 
      class="chart-out-box" 
      ref="boxRef"
      :style="boxStyle"
    >
      <div class="chart-wrapper" ref="chartRef"></div>

      <div class="zoom-controls">
        <n-button-group vertical>
          <n-button secondary circle @click="handleZoom(1.2)">
            <template #icon><n-icon><Add /></n-icon></template>
          </n-button>
          <n-button secondary circle @click="handleZoom(0.8)">
            <template #icon><n-icon><Remove /></n-icon></template>
          </n-button>
        </n-button-group>
      </div>

      <div class="resize-handle right" @mousedown.prevent="startResize($event, 'width')"></div>
      <div class="resize-handle bottom" @mousedown.prevent="startResize($event, 'height')"></div>
      <div class="resize-handle corner" @mousedown.prevent="startResize($event, 'both')">
        <n-icon size="16" color="#aaa"><ResizeOutline /></n-icon>
      </div>
    </div>
    
    <div v-if="loading" class="loading-mask">
      <n-spin size="large" description="正在加载星图..." />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted, onUnmounted, nextTick, watch, computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { NButton, NButtonGroup, NIcon, NSpin, useMessage, useThemeVars } from 'naive-ui'
import { ArrowBack, Play, Add, Remove, ResizeOutline } from '@vicons/ionicons5' // 引入 Resize 图标
import * as echarts from 'echarts'
import request from '../api/request'

const route = useRoute()
const router = useRouter()
const message = useMessage()
const themeVars = useThemeVars()

const graphId = route.params.id
const chartRef = ref<HTMLElement | null>(null)
const boxRef = ref<HTMLElement | null>(null)      // 【新增】引用外层盒子
const containerRef = ref<HTMLElement | null>(null)// 【新增】引用最外层容器
const loading = ref(true)
const graphName = ref('加载中...')
const nodeCount = ref(0)
const currentZoom = ref(0.3)

let myChart: echarts.ECharts | null = null
let resizeObserver: ResizeObserver | null = null

// ================== 拖拽缩放逻辑开始 ==================

// 记录盒子尺寸状态
const boxState = reactive({
  isResizing: false,
  width: 0,  // 0 表示自动(flex: 1)
  height: 0,
  startX: 0,
  startY: 0,
  startWidth: 0,
  startHeight: 0,
  resizeMode: '' as 'width' | 'height' | 'both'
})

// 计算动态样式
const boxStyle = computed(() => {
  const style: any = {}
  // 如果正在调整或已经调整过，则使用固定尺寸
  if (boxState.width > 0) style.width = `${boxState.width}px`
  if (boxState.height > 0) style.height = `${boxState.height}px`
  
  // 如果设置了尺寸，取消 flex: 1，改为 flex: none 以便生效
  if (boxState.width > 0 || boxState.height > 0) {
    style.flex = 'none'
  }
  return style
})

const startResize = (e: MouseEvent, mode: 'width' | 'height' | 'both') => {
  if (!boxRef.value) return

  boxState.isResizing = true
  boxState.resizeMode = mode
  boxState.startX = e.clientX
  boxState.startY = e.clientY

  // 获取当前实际尺寸作为起始值
  const rect = boxRef.value.getBoundingClientRect()
  boxState.startWidth = rect.width
  boxState.startHeight = rect.height
  
  // 如果是第一次拖动，初始化当前尺寸，防止跳变
  if (boxState.width === 0) boxState.width = rect.width
  if (boxState.height === 0) boxState.height = rect.height

  // 添加全局事件监听
  document.addEventListener('mousemove', onMouseMove)
  document.addEventListener('mouseup', onMouseUp)
  document.body.style.userSelect = 'none' // 防止拖动时选中文字
  document.body.style.cursor = mode === 'both' ? 'nwse-resize' : (mode === 'width' ? 'ew-resize' : 'ns-resize')
}

const onMouseMove = (e: MouseEvent) => {
  if (!boxState.isResizing) return

  const dx = e.clientX - boxState.startX
  const dy = e.clientY - boxState.startY

  // 限制最小尺寸
  const minSize = 200

  if (boxState.resizeMode === 'width' || boxState.resizeMode === 'both') {
    boxState.width = Math.max(minSize, boxState.startWidth + dx)
  }
  if (boxState.resizeMode === 'height' || boxState.resizeMode === 'both') {
    boxState.height = Math.max(minSize, boxState.startHeight + dy)
  }
}

const onMouseUp = () => {
  boxState.isResizing = false
  document.removeEventListener('mousemove', onMouseMove)
  document.removeEventListener('mouseup', onMouseUp)
  document.body.style.userSelect = ''
  document.body.style.cursor = ''
  
  // 触发一次图表重绘（虽然 ResizeObserver 会处理，但手动触发更稳妥）
  myChart?.resize()
}

// ================== 拖拽缩放逻辑结束 ==================

const goBack = () => {
  router.push('/')
}

const themeBlue = '#66ccff'

const handleZoom = (ratio: number) => {
  if (!myChart) return
  currentZoom.value *= ratio
  if (currentZoom.value < 0.1) currentZoom.value = 0.1
  if (currentZoom.value > 10) currentZoom.value = 10
  myChart.setOption({ series: [{ zoom: currentZoom.value }] })
}

const initChart = (nodes: any[], links: any[]) => {
  if (!chartRef.value) return
  if (chartRef.value.clientWidth === 0 || chartRef.value.clientHeight === 0) return

  if (myChart) myChart.dispose()

  myChart = echarts.init(chartRef.value)
  
  const tooltipBg = themeVars.value.cardColor
  const borderColor = themeVars.value.borderColor
  const textColor = themeVars.value.textColorBase

  const option = {
    backgroundColor: 'transparent',
    title: { show: false },
    tooltip: {
      trigger: 'item',
      backgroundColor: tooltipBg,
      borderColor: borderColor,
      textStyle: { color: textColor },
      formatter: (params: any) => {
        if (params.dataType === 'node') {
          return `<b>${params.data.name}</b><br/>歌手: ${params.data.artist}`
        }
        return `${params.data.source} -> ${params.data.target}<br/>权重: ${params.data.value}`
      }
    },
    series: [
      {
        type: 'graph',
        layout: 'force',
        layoutAnimation: true,
        zoom: currentZoom.value,
        label: { show: true, position: 'right', color: themeBlue, fontSize: 12 },
        data: nodes.map(n => ({
          id: n.id,
          name: n.name,
          symbolSize: n.symbolSize,
          value: n.artist,
          artist: n.artist,
          x: n.x, y: n.y,
          itemStyle: { color: themeBlue, borderColor: '#4dabf7', borderWidth: 1, shadowBlur: 10, shadowColor: 'rgba(102, 204, 255, 0.5)' }
        })),
        links: links.map(l => ({
          source: l.source, target: l.target, value: l.value,
          lineStyle: { width: Math.min(l.value, 5), curveness: 0.2, color: themeBlue, opacity: 0.3 }
        })),
        roam: true,
        edgeSymbol: ['none', 'arrow'],
        edgeSymbolSize: [4, 10],
        force: { repulsion: 400, edgeLength: [50, 200], gravity: 0.1 }
      }
    ]
  }

  myChart.setOption(option)
  
  myChart.on('click', (params) => {
    if (params.dataType === 'node') message.info(`选中歌曲: ${params.data.name}`)
  })
  myChart.on('graphRoam', (params: any) => {
    if (params.zoom) currentZoom.value *= params.zoom
  })
}

watch(() => themeVars.value, (newVars) => {
  if (myChart) {
    myChart.setOption({
      tooltip: { backgroundColor: newVars.cardColor, borderColor: newVars.borderColor, textStyle: { color: newVars.textColorBase } }
    })
  }
}, { deep: true })

let cachedNodes: any[] = []
let cachedLinks: any[] = []

const fetchData = async () => {
  loading.value = true
  try {
    const res = await request.get(`/graph/data/${graphId}`)
    const { nodes, links } = res.data
    nodeCount.value = nodes.length
    graphName.value = `图谱 #${graphId}`
    cachedNodes = nodes.map((n: any) => ({ ...n, x: Math.random() * 800, y: Math.random() * 600 }))
    cachedLinks = links
    await nextTick()
    initChart(cachedNodes, cachedLinks)
  } catch (err) {
    message.error('无法加载图谱数据')
  } finally {
    loading.value = false
  }
}

const handleResize = () => {
  if (myChart) myChart.resize()
  else if (cachedNodes.length > 0) initChart(cachedNodes, cachedLinks)
}

onMounted(async () => {
  // 【新增】初始化盒子大小和位置
  if (containerRef.value) {
    const cw = containerRef.value.clientWidth
    const ch = containerRef.value.clientHeight
    
    // 设置为屏幕宽度的 65%，高度减去头部和一些边距
    boxState.width = Math.max(300, Math.floor(cw * 0.5))
    boxState.height = Math.max(800, Math.floor(ch - 100))
  }

  if (chartRef.value) {
    resizeObserver = new ResizeObserver(() => handleResize())
    resizeObserver.observe(chartRef.value)
  }
  await fetchData()
})

onUnmounted(() => {
  if (resizeObserver) resizeObserver.disconnect()
  myChart?.dispose()
  document.removeEventListener('mousemove', onMouseMove)
  document.removeEventListener('mouseup', onMouseUp)
})
</script>

<style scoped>
.player-container {
  flex: 1;
  width: 100%;
  display: flex;
  flex-direction: column;
  position: relative;
  background-color: var(--n-body-color);
  overflow: hidden; /* 防止拖动过大撑开滚动条 */
}

.player-header {
  height: 60px;
  padding: 0 20px;
  display: flex;
  justify-content: space-between;
  align-items: center;
  background-color: var(--n-card-color);
  border-bottom: 1px solid var(--n-border-color);
  z-index: 10;
  flex: none; /* 头部不参与 flex 伸缩 */
}

.left { display: flex; align-items: center; gap: 15px; }
.info h2 { margin: 0; font-size: 1.1rem; color: var(--n-text-color); }
.info .status { font-size: 0.8rem; color: var(--n-text-color-3); }

/* 容器样式调整 */
.chart-out-box {
  /* 默认 flex: 1，当 JS 设置 width/height 后这里会被覆盖为 flex: none */
  flex: 1; 
  padding: 10px;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  position: relative; 
  
  /* 【修改】靠右对齐：上 右 下 左。左边 auto 会把元素推向右边 */
  margin: 20px 20px 20px auto;
  
  border: 2px dashed v-bind('themeVars.borderColor');
  border-radius: 12px;
  background-color: v-bind('themeVars.tableColor');
  box-sizing: border-box; /* 关键：包含 padding 和 border */
  min-width: 300px;
  min-height: 300px;
  transition: border-color 0.3s;
}

/* 激活状态的边框高亮 */
.chart-out-box:hover {
  border-color: var(--n-primary-color);
}

.chart-wrapper {
  flex: 1;
  width: 100%;
  /* 移除最小高度限制，完全跟随父容器 */
  height: 100%; 
  overflow: hidden;
  border: 2px solid v-bind('themeVars.borderColor'); 
  border-radius: 16px;
  background-color: v-bind('themeVars.cardColor');
  box-sizing: border-box;
}

.zoom-controls {
  position: absolute;
  bottom: 40px;
  right: 40px;
  z-index: 90; /* 略低于 resize handle */
  background-color: var(--n-card-color);
  border-radius: 4px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.15);
}

.loading-mask {
  position: absolute;
  top: 60px;
  left: 0;
  right: 0;
  bottom: 0;
  display: flex;
  justify-content: center;
  align-items: center;
  background-color: var(--n-color-modal);
  z-index: 20;
  backdrop-filter: blur(2px);
}

/* ================== 拖拽手柄样式 ================== */
.resize-handle {
  position: absolute;
  z-index: 100;
  transition: background-color 0.2s;
}

/* 右边框感应区 */
.resize-handle.right {
  top: 0;
  right: -5px; /* 向外延伸一点方便抓取 */
  bottom: 20px; /* 留出角落 */
  width: 15px;
  cursor: ew-resize;
}

/* 下边框感应区 */
.resize-handle.bottom {
  bottom: -5px;
  left: 0;
  right: 20px;
  height: 15px;
  cursor: ns-resize;
}

/* 右下角拖拽点 */
.resize-handle.corner {
  bottom: 0;
  right: 0;
  width: 30px;
  height: 30px;
  cursor: nwse-resize;
  display: flex;
  align-items: center;
  justify-content: center;
  background: var(--n-card-color); /* 给个背景色挡住线条 */
  border-top-left-radius: 8px;
  border: 1px solid var(--n-border-color);
}
.resize-handle.corner:hover {
  background: var(--n-action-color);
}
</style>
